// <auto-generated />
using System;
using BsBakerySPA.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BsBakerySPA.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250424193840_UpdateSeedDataFromProductsJsx")]
    partial class UpdateSeedDataFromProductsJsx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("BsBakerySPA.Server.Models.BagelTopping", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BagelToppings");

                    b.HasData(
                        new
                        {
                            Id = "T000",
                            Name = "Plain"
                        },
                        new
                        {
                            Id = "T001",
                            Name = "Cheddar"
                        },
                        new
                        {
                            Id = "T002",
                            Name = "Asiago"
                        },
                        new
                        {
                            Id = "T003",
                            Name = "Sesame"
                        },
                        new
                        {
                            Id = "T004",
                            Name = "Everything"
                        },
                        new
                        {
                            Id = "T005",
                            Name = "Cheddar Jalapeño"
                        });
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserFirebaseUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("UserFirebaseUid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BagelDistributionJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerItem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedToppingIdsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "L001",
                            Category = "Loaf",
                            Name = "Regular",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = "L002",
                            Category = "Loaf",
                            Name = "Pepperoni Mozzarella",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = "L003",
                            Category = "Loaf",
                            Name = "Cheddar Jalapeño",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = "L004",
                            Category = "Loaf",
                            Name = "Cinnamon Apple",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = "L005",
                            Category = "Loaf",
                            Name = "Everything Loaf",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = "B001",
                            Category = "Bagel",
                            Name = "1/2 Dozen Bagels",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = "B002",
                            Category = "Bagel",
                            Name = "Dozen Bagels",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = "C001",
                            Category = "Cookie",
                            Name = "Chocolate Chip Cookies (Dozen)",
                            Price = 20.00m
                        });
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestModels");
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.User", b =>
                {
                    b.Property<string>("FirebaseUid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FirebaseUid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.Order", b =>
                {
                    b.HasOne("BsBakerySPA.Server.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserFirebaseUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.OrderItem", b =>
                {
                    b.HasOne("BsBakerySPA.Server.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BsBakerySPA.Server.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
